OpenAI/Packages/com.openai.unity/README.md, OpenAI/Packages/com.openai.unity/Runtime/AuthInfo.cs, OpenAI/Packages/com.openai.unity/Runtime/AuthInfo.cs.meta, OpenAI/Packages/com.openai.unity/Runtime/OpenAIAuthentication.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIClient.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIConfigurationSettings.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_00_Authentication.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_04_Images.cs, OpenAI/Packages/com.openai.unity/package.json, README.md
- Closes #15 
- Updated documentation
=>  com.openai.unity 2.0.0-preview.6

OpenAI/Packages/com.openai.unity/Runtime/OpenAIAuthentication.cs
removed ability to set Default config (internal set only for testing)
=> fixed issue loading json config when searching directories

OpenAI/Packages/com.openai.unity/Editor/FineTuning/FineTuningWindow.cs, OpenAI/Packages/com.openai.unity/Runtime/FineTuning/FineTuningTrainingDataSet.cs, OpenAI/Packages/com.openai.unity/package.json
- Show an error helpbox in training window if no api key is set
- Update the default training base model
=> com.openai.unity 2.2.1

OpenAI/Packages/com.openai.unity/Documentation~/README.md, OpenAI/Packages/com.openai.unity/Runtime/Chat.meta, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatEndpoint.cs.meta, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatPrompt.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatPrompt.cs.meta, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatRequest.cs.meta, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatResponse.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatResponse.cs.meta, OpenAI/Packages/com.openai.unity/Runtime/Chat/Choice.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/Choice.cs.meta, OpenAI/Packages/com.openai.unity/Runtime/Chat/Message.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/Message.cs.meta, OpenAI/Packages/com.openai.unity/Runtime/Completions/CompletionsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Embeddings/EmbeddingsRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Files/FilesEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/FineTuning/FineTuningEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Images/ImagesEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Models/Model.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIClient.cs, OpenAI/Packages/com.openai.unity/Runtime/ResponseExtensions.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_03_Chat.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_03_Chat.cs.meta, OpenAI/Packages/com.openai.unity/package.json, README.md
=> com.openai.unity 3.0.0

OpenAI/Packages/com.openai.unity/Documentation~/README.md, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatPrompt.cs.meta, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatRequest.cs.meta, OpenAI/Packages/com.openai.unity/Tests/TestFixture_03_Chat.cs.meta, OpenAI/Packages/com.openai.unity/package.json
- Fixed missing icons
- Fixed chat parameters
- Removed spam logging leftover from testing
- Updated docs
=>  com.openai.unity 3.0.1

OpenAI/Packages/com.openai.unity/Editor/FineTuning/FineTuningWindow.cs, OpenAI/Packages/com.openai.unity/Runtime/Models/ModelsEndpoint.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_09_FineTuning.cs, OpenAI/Packages/com.openai.unity/package.json
- Fixed an issue when attempting to delete fine tuned model owned by personal account
=> com.openai.unity 3.1.3

OpenAI/Packages/com.openai.unity/Documentation~/README.md, OpenAI/Packages/com.openai.unity/Runtime/Audio/AudioEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/BaseEndPoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Completions/CompletionsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Edits/EditsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Embeddings/EmbeddingsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Files/FilesEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/FineTuning/FineTuningEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Images/ImagesEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Models/ModelsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Moderations/ModerationsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIClient.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIClientSettings.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIClientSettings.cs.meta, OpenAI/Packages/com.openai.unity/package.json, README.md
- Added support for Azure OpenAI
=> com.openai.unity 4.0.0

OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Models/Model.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIAuthentication.cs, OpenAI/Packages/com.openai.unity/package.json
- Added support for gpt-4 models
=> com.openai.unity 4.1.0

OpenAI/Packages/com.openai.unity/Documentation~/README.md, OpenAI/Packages/com.openai.unity/Runtime/AuthInfo.cs, OpenAI/Packages/com.openai.unity/Runtime/BaseEndPoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Completions/CompletionsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/FineTuning/FineTuningEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIClient.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIClientSettings.cs, OpenAI/Packages/com.openai.unity/Runtime/ResponseExtensions.cs, OpenAI/Packages/com.openai.unity/package.json, README.md
- 🔥 4.2.0 blaze it
- Added support for [OpenAI-DotNet-Proxy](https://github.com/RageAgainstThePixel/OpenAI-DotNet/pull/46)
- Added support for custom domains
- Minor refactoring
- Updated docs
=> com.openai.unity 4.2.0

OpenAI/Packages/com.openai.unity/Documentation~/README.md, OpenAI/Packages/com.openai.unity/Editor/OpenAIConfigurationSettingsInspector.cs, OpenAI/Packages/com.openai.unity/Runtime/Audio/AudioEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Completions/CompletionsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Embeddings/EmbeddingsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Files/FilesEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/FineTuning/FineTuningEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Images/ImagesEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Models/ModelsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIClient.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIClientSettings.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIConfigurationSettings.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_01_Models.cs, OpenAI/Packages/com.openai.unity/package.json, README.md
- added better support for OpenAI on Azure in configuration settings
- ensure event callbacks are raised on the unity main thread
- updated docs
- updated unit tests
=> com.openai.unity 4.3.0

OpenAI/Packages/com.openai.unity/Runtime/Files/FilesEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/FineTuning/FineTuningEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/FineTuning/FineTuningTrainingData.cs, OpenAI/Packages/com.openai.unity/Runtime/FineTuning/FineTuningTrainingDataSet.cs, OpenAI/Packages/com.openai.unity/package.json
- Make a few classes sealed that are not meant to be extended
=> com.openai.unity 4.3.1

OpenAI/Packages/com.openai.unity/Runtime/Images/ImageEditRequest.cs, OpenAI/Packages/com.openai.unity/package.json
- Fixes https://github.com/RageAgainstThePixel/OpenAI-DotNet/issues/64
- Added ImageEditRequest overloads for optional mask parameter
=> com.openai.unity 4.4.1

OpenAI/Packages/com.openai.unity/Editor/FineTuning/FineTuningWindow.cs, OpenAI/Packages/com.openai.unity/Editor/OpenAI.Editor.asmdef, OpenAI/Packages/com.openai.unity/Editor/OpenAIConfigurationSettingsInspector.cs, OpenAI/Packages/com.openai.unity/Runtime/Files/FilesEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIClient.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIClientSettings.cs, OpenAI/Packages/com.openai.unity/Tests/OpenAI.Tests.asmdef, OpenAI/Packages/com.openai.unity/package.json
- updated dependencies
- fixed some issues with config settings not updating after inputting new values
- misc fixes and changes for dependencies
=> com.openai.unity 4.4.2

OpenAI/Packages/com.openai.unity/Documentation~/README.md, OpenAI/Packages/com.openai.unity/Editor/FineTuning/FineTuningWindow.cs, OpenAI/Packages/com.openai.unity/Editor/OpenAIConfigurationSettingsInspector.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIClient.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIClientSettings.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIConfigurationSettings.cs, OpenAI/Packages/com.openai.unity/package.json, README.md
- Fixed support for Azure Active Directory authentication for Azure OpenAI
- Updated docs
- Fixed some issues with Fine Tuning window when no apiKey is set
=> com.openai.unity 4.4.3

OpenAI/Packages/com.openai.unity/Documentation~/README.md, OpenAI/Packages/com.openai.unity/Runtime/Edits/Choice.cs, OpenAI/Packages/com.openai.unity/Runtime/Edits/EditRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Edits/EditResponse.cs, OpenAI/Packages/com.openai.unity/Runtime/Edits/EditsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIClient.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_04_Edits.cs, OpenAI/Packages/com.openai.unity/package.json, README.md
- Marked EditEndpoint Obsolete as codex and edit models have been removed
=> com.openai.unity 4.5.0

OpenAI/Packages/com.openai.unity/Documentation~/README.md, OpenAI/Packages/com.openai.unity/Runtime/Edits/Choice.cs, OpenAI/Packages/com.openai.unity/Runtime/Edits/EditRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Edits/EditResponse.cs, OpenAI/Packages/com.openai.unity/Runtime/Edits/EditsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIClient.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_04_Edits.cs, OpenAI/Packages/com.openai.unity/package.json, README.md
- Removed Obsolete from EditEndpoint as it has now been fixed by OpenAI
=> com.openai.unity 4.5.1

OpenAI/Packages/com.openai.unity/Documentation~/README.md, OpenAI/Packages/com.openai.unity/package.json, README.md
=> com.openai.unity 4.5.3

OpenAI/Packages/com.openai.unity/package.json, OpenAI/ProjectSettings/ProjectVersion.txt
=> com.openai.unity 4.5.4

OpenAI/Packages/com.openai.unity/Documentation~/README.md, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatResponse.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/Delta.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/Message.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIAuthentication.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_00_Authentication.cs, OpenAI/Packages/com.openai.unity/package.json, OpenAI/Packages/manifest.json, README.md
- Made it easier to specify a specific configuration file path
- Added optional author name property to chat message
- Added implicit string conversions to make ChatResponses easier to work with
- Updated docs
- Updated deps
=> com.openai.unity 4.7.2

OpenAI/Packages/com.openai.unity/Runtime/Models/Model.cs, OpenAI/Packages/com.openai.unity/Runtime/Models/ModelsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Models/Permission.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_01_Models.cs, OpenAI/Packages/com.openai.unity/package.json
- fixed Model.Permissions
- added Model.CreatedAt
=> com.openai.unity 4.7.4

OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/Choice.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/Delta.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/Message.cs, OpenAI/Packages/com.openai.unity/Runtime/Completions/Choice.cs, OpenAI/Packages/com.openai.unity/Runtime/Completions/CompletionResult.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIClient.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_03_Chat.cs, OpenAI/Packages/com.openai.unity/package.json
- Updated basic and chat completions choices to default to empty string
- Fixed Completions.CompletionResult.ToString first completion index lookup
=> com.openai.unity 4.8.1

OpenAI/Packages/com.openai.unity/Runtime/BaseEndPoint.cs, OpenAI/Packages/com.openai.unity/package.json
- Revert BaseEndpoint.GetUrl changes
=> com.openai.unity 4.8.4

OpenAI/Packages/com.openai.unity/Runtime/Audio/AudioEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Audio/AudioTranscriptionRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Audio/AudioTranslationRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Completions/CompletionRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Completions/CompletionsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Edits/EditRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Embeddings/EmbeddingsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Embeddings/EmbeddingsRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Models/Model.cs, OpenAI/Packages/com.openai.unity/Runtime/Moderations/ModerationsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Moderations/ModerationsRequest.cs
Updated all method calls to take a model as string
=> Model updates

OpenAI/Packages/com.openai.unity/Runtime/Audio/AudioEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Audio/AudioTranscriptionRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Audio/AudioTranslationRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Completions/CompletionRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Completions/CompletionsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Edits/EditRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Embeddings/EmbeddingsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Embeddings/EmbeddingsRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Models/Model.cs, OpenAI/Packages/com.openai.unity/Runtime/Models/ModelsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Moderations/ModerationsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Moderations/ModerationsRequest.cs, OpenAI/Packages/com.openai.unity/package.json
Updated all method calls to take a model as string
=> com.openai.unity 4.8.5

OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatEndpoint.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_03_Chat.cs, OpenAI/Packages/com.openai.unity/package.json
- Populated finish reason in streaming chat final message content
=> com.openai.unity 4.8.6

.gitignore, OpenAI/Assets/Demo/Chat/ChatDemo.cs, OpenAI/Assets/Demo/Chat/ChatDemo.unity, OpenAI/Packages/com.openai.unity/Editor/FineTuning/FineTuningWindow.cs, OpenAI/Packages/com.openai.unity/Runtime/Audio/AudioEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Completions/CompletionsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Edits/EditsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Embeddings/EmbeddingsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Extensions/ResponseExtensions.cs, OpenAI/Packages/com.openai.unity/Runtime/Files/FilesEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/FineTuning/FineTuningEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Images/ImagesEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Models/ModelsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Moderations/ModerationsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIClient.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_02_Completions.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_03_Chat.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_06_Embeddings.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_09_FineTuning.cs, OpenAI/Packages/com.openai.unity/package.json, OpenAI/Packages/manifest.json, OpenAI/ProjectSettings/ProjectSettings.asset
- enables WebGL support
- https://github.com/RageAgainstThePixel/com.utilities.rest/pull/26
=> feat: remove HttpClient

OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatResponse.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/Message.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_03_Chat.cs, OpenAI/Packages/com.openai.unity/package.json
- Fixed chat streaming message copy from delta
=> com.openai.unity 5.0.3

OpenAI/Packages/com.openai.unity/Documentation~/README.md, OpenAI/Packages/com.openai.unity/Runtime/Chat/Message.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_03_Chat.cs, OpenAI/Packages/com.openai.unity/package.json, OpenAI/ProjectSettings/ProjectVersion.txt, README.md
- Fixed Message.Content serialization in Role.Function message history
=> com.openai.unity 5.0.5

OpenAI/Packages/com.openai.unity/Runtime/Common/Usage.cs, OpenAI/Packages/com.openai.unity/Runtime/Embeddings/Datum.cs, OpenAI/Packages/com.openai.unity/Runtime/Embeddings/EmbeddingsResponse.cs, OpenAI/Packages/com.openai.unity/package.json
- fixed embedding response deserialization
=> com.openai.unity 5.0.6

OpenAI/Packages/com.openai.unity/package.json
- bump com.utilities.rest -> 2.1.4
=> com.openai.unity 5.0.7

OpenAI/Packages/com.openai.unity/Runtime/Audio/AudioTranscriptionRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Moderations/Categories.cs, OpenAI/Packages/com.openai.unity/Runtime/Moderations/ModerationResult.cs, OpenAI/Packages/com.openai.unity/Runtime/Moderations/Scores.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_07_Audio.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_10_Moderations.cs, OpenAI/Packages/com.openai.unity/package.json, OpenAI/Packages/manifest.json
- Fixed AudioTranscriptionRequest.Temperature type. int? -> float?
- Updated Moderations Categories and Scores with new metrics
=> com.openai.unity 5.0.8

OpenAI/Packages/com.openai.unity/Editor/FineTuning/FineTuningWindow.cs, OpenAI/Packages/com.openai.unity/Runtime/Models/ModelsEndpoint.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_09_FineTuning.cs, OpenAI/Packages/com.openai.unity/package.json
- Fixed Model delete permission Unauthorized Access check
=> com.openai.unity 5.0.9

OpenAI/Packages/com.openai.unity/package.json, OpenAI/Packages/manifest.json
- updated rest package to fix incomplete chat stream data responses
=> com.openai.unity 5.0.11

OpenAI/Packages/com.openai.unity/Documentation~/README.md, OpenAI/Packages/com.openai.unity/Runtime/Files/FilesEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Images/AbstractBaseImageRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Images/ImageEditRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Images/ImagesEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIClient.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_05_Images.cs, OpenAI/Packages/com.openai.unity/package.json, README.md
- mark some image endpoint functions obsolete in favor of image request types
- updated docs
=> com.openai.unity 5.1.1

OpenAI/Packages/com.openai.unity/Runtime/Images/ImagesEndpoint.cs, OpenAI/Packages/com.openai.unity/package.json
- Fix Image Generation result local cache file path
=> com.openai.unity 5.1.2

OpenAI/Packages/com.openai.unity/Runtime/Images/ImagesEndpoint.cs, OpenAI/Packages/com.openai.unity/package.json
- Fix Image Generation result local cache file path (for real!)
=> com.openai.unity 5.1.3

OpenAI/Packages/com.openai.unity/Documentation~/README.md, OpenAI/Packages/com.openai.unity/Runtime/Audio/AudioEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Audio/SpeechRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatResponseFormat.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/Content.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/ContentType.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/Conversation.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/FinishDetails.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/ImageUrl.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/Message.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/ResponseFormat.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/Tool.cs, OpenAI/Packages/com.openai.unity/Runtime/Extensions/StringExtensions.cs, OpenAI/Packages/com.openai.unity/Samples~/Chat/ChatBehaviour.cs, OpenAI/Packages/com.openai.unity/Samples~/Chat/OpenAIChatSample.unity, OpenAI/Packages/com.openai.unity/Tests/TestFixture_03_Chat.cs, OpenAI/Packages/com.openai.unity/package.json, OpenAI/ProjectSettings/ProjectSettings.asset, README.md
- Removed dynamic types in favor of object to fix crashing on il2cpp
- Added additional Preserve attributes and constructors to stripped types
- Changed tts clip download cache location
- Updated chat samples package with tts voice of assistant
- Added ability to reference a Texture2D object for vision requests
- Updated docs
=> com.openai.unity 5.2.1

OpenAI/Packages/com.openai.unity/Runtime/Chat/Content.cs, OpenAI/Packages/com.openai.unity/Runtime/Images/ImagesEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAISettingsInfo.cs, OpenAI/Packages/com.openai.unity/package.json, OpenAI/ProjectSettings/EditorBuildSettings.asset
- Fixed Image Generation for Azure
=> com.openai.unity 5.2.2

.github/workflows/upm-subtree-split.yml, OpenAI/Packages/com.openai.unity/Documentation~/README.md, OpenAI/Packages/com.openai.unity/Runtime/Audio/AudioTranscriptionRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Audio/AudioTranslationRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAI.asmdef, OpenAI/Packages/com.openai.unity/package.json, OpenAI/Packages/manifest.json, README.md
- switched audio encoding from wav to ogg
- changed Audio.TranscriptionRequest.Temperature int? -> float?
=> com.openai.unity 5.2.3

OpenAI/Packages/com.openai.unity/Documentation~/README.md, OpenAI/Packages/com.openai.unity/Runtime/Assistants/AssistantExtensions.cs, OpenAI/Packages/com.openai.unity/Runtime/Common/ContentType.cs, OpenAI/Packages/com.openai.unity/Runtime/Common/ImageFile.cs, OpenAI/Packages/com.openai.unity/Runtime/Common/ImageFile.cs.meta, OpenAI/Packages/com.openai.unity/Runtime/Completions/Choice.cs, OpenAI/Packages/com.openai.unity/Runtime/Completions/CompletionResponse.cs, OpenAI/Packages/com.openai.unity/Runtime/Completions/CompletionsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Completions/LogProbabilities.cs, OpenAI/Packages/com.openai.unity/Runtime/Edits/Choice.cs, OpenAI/Packages/com.openai.unity/Runtime/Edits/EditRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Edits/EditResponse.cs, OpenAI/Packages/com.openai.unity/Runtime/Edits/EditsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIClient.cs, OpenAI/Packages/com.openai.unity/Runtime/Threads/Content.cs, OpenAI/Packages/com.openai.unity/Runtime/Threads/ThreadExtensions.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_02_Completions.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_11_Assistants.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_12_Threads.cs, OpenAI/Packages/com.openai.unity/package.json, README.md
- Fixed missing Threads.Message.Content.ImageFile property.
- Marked OpenAI.Completions Obsolete
=> com.openai.unity 7.0.2

OpenAI/Packages/com.openai.unity/Runtime/Authentication/OpenAISettings.cs, OpenAI/Packages/com.openai.unity/package.json, OpenAI/ProjectSettings/ProjectVersion.txt
- Fixed OpenAISettings configuration lookup
=> com.openai.unity 7.0.5

OpenAI/Packages/com.openai.unity/Editor/FineTuning/FineTuningWindow.cs, OpenAI/Packages/com.openai.unity/package.json
=> com.openai.unity 7.1.1

OpenAI/Packages/com.openai.unity/Runtime/Assistants/AssistantExtensions.cs, OpenAI/Packages/com.openai.unity/Runtime/Assistants/AssistantResponse.cs, OpenAI/Packages/com.openai.unity/Runtime/Assistants/CreateAssistantRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Threads/CreateThreadRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Threads/Message.cs, OpenAI/Packages/com.openai.unity/Runtime/Threads/MessageResponse.cs, OpenAI/Packages/com.openai.unity/Runtime/Threads/RunResponse.cs, OpenAI/Packages/com.openai.unity/Runtime/Threads/RunStepResponse.cs, OpenAI/Packages/com.openai.unity/Runtime/Threads/ThreadResponse.cs, OpenAI/Packages/com.openai.unity/package.json
- Fixed dictionary metadata deserialization for AOT platforms
=> com.openai.unity 7.1.3

OpenAI/Packages/com.openai.unity/Runtime/Chat/Message.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIClient.cs, OpenAI/Packages/com.openai.unity/package.json
- removed EmptyToNullStringContractResolver from global json serialization settings
- updated Chat.Message.CopyFrom content check from string.IsNullOrEmpty to null check
- updated Chat.Message.CopyFrom to directly assign content backing field
=> com.openai.unity 7.1.4

OpenAI/Packages/com.openai.unity/Runtime/Images/ImageResult.cs, OpenAI/Packages/com.openai.unity/Runtime/Images/ImagesEndpoint.cs, OpenAI/Packages/com.openai.unity/package.json
- fix ImageResult.CacheedPath calculation
=> com.openai.unity 7.2.1

OpenAI/Packages/com.openai.unity/Runtime/Assistants/AssistantExtensions.cs, OpenAI/Packages/com.openai.unity/Runtime/Files/FileUploadRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Threads/CreateMessageRequest.cs, OpenAI/Packages/com.openai.unity/package.json
- Fixed parameter name in Threads.CreateMessageRequest
- Added Stream overload to Threads.FileUploadRequest
=> com.openai.unity 7.3.2

OpenAI/Packages/com.openai.unity/Runtime/Audio/AudioEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Common/ImageFile.cs, OpenAI/Packages/com.openai.unity/Runtime/Embeddings/EmbeddingsEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Embeddings/EmbeddingsRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Files/FilesEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Images/ImagesEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Models/Model.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIClient.cs, OpenAI/Packages/com.openai.unity/Runtime/Threads/CodeInterpreter.cs, OpenAI/Packages/com.openai.unity/Runtime/Threads/CodeInterpreter.cs.meta, OpenAI/Packages/com.openai.unity/Runtime/Threads/CodeInterpreterOutputType.cs, OpenAI/Packages/com.openai.unity/Runtime/Threads/CodeInterpreterOutputType.cs.meta, OpenAI/Packages/com.openai.unity/Runtime/Threads/CodeInterpreterOutputs.cs, OpenAI/Packages/com.openai.unity/Runtime/Threads/CodeInterpreterOutputs.cs.meta, OpenAI/Packages/com.openai.unity/Runtime/Threads/RunResponse.cs, OpenAI/Packages/com.openai.unity/Runtime/Threads/RunStepResponse.cs, OpenAI/Packages/com.openai.unity/Runtime/Threads/ToolCall.cs, OpenAI/Packages/com.openai.unity/Samples~/Chat/ChatBehaviour.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_06_Embeddings.cs, OpenAI/Packages/com.openai.unity/package.json, OpenAI/Packages/manifest.json
- Added new Embedding Models
- Added Model.Dimensions property
- Added Threads.Run and Threads.RunStep Usage properties
- Added CodeInterpreter Outputs to RunStepDetails.ToolCalls
- Added Retrieval Outputs to RunStepDetails.ToolCalls
=> com.openai.unity 7.3.3

OpenAI/Packages/com.openai.unity/Runtime/Audio/AudioEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/OpenAIClient.cs, OpenAI/Packages/com.openai.unity/package.json
- Updated api key prefix checks to only be enforced for OpenAI domain
- Fixed file name collisions when generating speech clips in parallel
=> com.openai.unity 7.3.5

OpenAI/Packages/com.openai.unity/package.json, OpenAI/Packages/manifest.json
- updated com.utilities.rest -> 2.5.2
- updated com.utilities.encoder.wav -> 1.1.5
=> com.openai.unity 7.3.6

OpenAI/Packages/com.openai.unity/Documentation~/README.md, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Common/Function.cs, OpenAI/Packages/com.openai.unity/Runtime/Common/FunctionParameterAttribute.cs, OpenAI/Packages/com.openai.unity/Runtime/Common/FunctionParameterAttribute.cs.meta, OpenAI/Packages/com.openai.unity/Runtime/Extensions/TypeExtensions.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_03_Chat.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_12_Threads.cs, OpenAI/Packages/com.openai.unity/Tests/Weather/WeatherService.cs, OpenAI/Packages/com.openai.unity/package.json, README.md
- Added FunctionParameterAttribute to help better inform the feature how to format the Function json
=> com.openai.unity 7.7.2

OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatRequest.cs, OpenAI/Packages/com.openai.unity/Tests/Weather/WeatherService.cs, OpenAI/Packages/com.openai.unity/package.json
- Updated ChatRequest toolChoice to only send type and name of function, reducing token usage
=> com.openai.unity 7.7.3

OpenAI/Packages/com.openai.unity/Runtime/Threads/MessageResponse.cs, OpenAI/Packages/com.openai.unity/Runtime/Threads/ThreadExtensions.cs, OpenAI/Packages/com.openai.unity/package.json
- Fixed Threads.RunResponse.WaitForStatusChangeAsync timeout
=> com.openai.unity 7.7.4

OpenAI/Packages/com.openai.unity/Samples~/Chat/ChatBehaviour.cs, OpenAI/Packages/com.openai.unity/package.json, OpenAI/ProjectSettings/ProjectVersion.txt
- Fixed Chat sample in 2021.3 LTS
=> com.openai.unity 7.7.9

OpenAI/Packages/com.openai.unity/Runtime/Threads/RunStatus.cs, OpenAI/Packages/com.openai.unity/Samples~/Chat/ChatBehaviour.cs, OpenAI/Packages/com.openai.unity/package.json
- Fixed Thread.Run.Status enum ordering
- Fixed sample scene
=> com.openai.unity 8.0.1

OpenAI/Packages/com.openai.unity/Runtime/Threads/MessageDelta.cs, OpenAI/Packages/com.openai.unity/Runtime/Threads/MessageResponse.cs, OpenAI/Packages/com.openai.unity/Runtime/Threads/RunResponse.cs, OpenAI/Packages/com.openai.unity/Runtime/Threads/RunStepResponse.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_03_Threads.cs, OpenAI/Packages/com.openai.unity/package.json
- Fixed Thread.MessageResponse and Thread.RunStepResponse Delta stream event objects not being properly populated
- Added Thread.MessageDelta.PrintContent()
- Added additional unit tests for delta objects
=> com.openai.unity 8.0.3

OpenAI/Assets/Samples, OpenAI/Assets/Samples.meta, OpenAI/Packages/com.openai.unity/Runtime/Common/Function.cs, OpenAI/Packages/com.openai.unity/Runtime/Common/Tool.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_00_02_Tools.cs, OpenAI/Packages/com.openai.unity/package.json, OpenAI/Packages/manifest.json, OpenAI/ProjectSettings/EditorBuildSettings.asset, OpenAI/ProjectSettings/ProjectSettings.asset, OpenAI/ProjectSettings/ProjectVersion.txt, README.md
- Added constructor overloads to Tool and Function classes to support manually adding tool calls in the conversation history
=> com.openai.unity 8.1.2

OpenAI/Packages/com.openai.unity/Runtime/Common/OpenAIBaseEndpoint.cs, OpenAI/Packages/com.openai.unity/package.json
- Fixed a typo in the Azure OpenAI URL base endpoint
=> com.openai.unity 8.2.1

OpenAI/Packages/com.openai.unity/package.json
=> com.openai.unity 8.2.3

OpenAI/Packages/com.openai.unity/Runtime/Assistants/AssistantResponse.cs, OpenAI/Packages/com.openai.unity/Runtime/Assistants/CreateAssistantRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Audio/AudioEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Common/BaseResponse.cs, OpenAI/Packages/com.openai.unity/Runtime/Common/FileSearchOptions.cs, OpenAI/Packages/com.openai.unity/Runtime/Common/RankingOptions.cs, OpenAI/Packages/com.openai.unity/Runtime/Common/RankingOptions.cs.meta, OpenAI/Packages/com.openai.unity/Runtime/Extensions/ResponseFormatConverter.cs, OpenAI/Packages/com.openai.unity/Runtime/Extensions/ResponseFormatConverter.cs.meta, OpenAI/Packages/com.openai.unity/Runtime/Files/FilesEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Images/ImagesEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Threads/CreateRunRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Threads/CreateThreadAndRunRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Threads/RunResponse.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_02_Assistants.cs, OpenAI/Packages/com.openai.unity/package.json
- Fixed ResponseObjectFormat deserialization when set to auto
- Added RankingOptions to FileSearchOptions
- Fixed potential memory leaks when uploading files to various endpoints
- Added timestamp values to BaseResponse to calculate rate limits
=> com.openai.unity 8.2.4

OpenAI/Packages/com.openai.unity/Runtime/Common/FileSearchOptions.cs, OpenAI/Packages/com.openai.unity/package.json, OpenAI/Packages/manifest.json
- Fixed ResponseObjectFormat deserialization when maxNumberOfResults is null
=> com.openai.unity 8.2.5

OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatRequest.cs, OpenAI/Packages/com.openai.unity/package.json
- Fix ChatRequest serialization for Azure OpenAI
=> com.openai.unity 8.4.1

OpenAI/Packages/com.openai.unity/Runtime/Chat/AudioConfig.cs, OpenAI/Packages/com.openai.unity/package.json
- fix improper usage in AudioConfig
=> com.openai.unity 8.4.2

OpenAI/Packages/com.openai.unity/Documentation~/README.md, OpenAI/Packages/com.openai.unity/Runtime/Realtime/ConversationItem.cs, OpenAI/Packages/com.openai.unity/package.json
- fixed docs
- fixed missing samples
=> com.openai.unity 8.4.3

OpenAI/Packages/com.openai.unity/Documentation~/README.md, OpenAI/Packages/com.openai.unity/Runtime/Audio/AudioEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Audio/SpeechClip.cs, OpenAI/Packages/com.openai.unity/Runtime/Audio/SpeechClip.cs.meta, OpenAI/Packages/com.openai.unity/Runtime/Realtime/ResponseAudioResponse.cs, OpenAI/Packages/com.openai.unity/Samples~/Assistant/AssistantBehaviour.cs, OpenAI/Packages/com.openai.unity/Samples~/Assistant/OpenAIAssistantSample.unity, OpenAI/Packages/com.openai.unity/Samples~/Chat/ChatBehaviour.cs, OpenAI/Packages/com.openai.unity/Samples~/Chat/OpenAIChatSample.unity, OpenAI/Packages/com.openai.unity/Samples~/Realtime/OpenAIRealtimeSample.unity, OpenAI/Packages/com.openai.unity/Samples~/Realtime/RealtimeBehaviour.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_07_Audio.cs, OpenAI/Packages/com.openai.unity/package.json, OpenAI/Packages/manifest.json, README.md
- refactored AudioEndpoint speech requests
- added AudioEndpoint.GetSpeechAsync
- deprecated AudioEndpoint.CreateSpeechAsync
- deprecated AudioEndpoint.CreateSpeechStreamAsync
- added SpeechClip response
- added Realtime.ResponseAudioResponse.AudioSamples
- updated all sample scenes with new OnAudioFilterRead examples for better playback
- updated unit tests
=> com.openai.unity 8.4.4

OpenAI/Packages/com.openai.unity/Runtime/Audio/SpeechClip.cs, OpenAI/Packages/com.openai.unity/Runtime/Authentication/OpenAISettingsInfo.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/AudioOutput.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatEndpoint.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatResponse.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/Delta.cs, OpenAI/Packages/com.openai.unity/Runtime/Chat/Message.cs, OpenAI/Packages/com.openai.unity/Runtime/Realtime/InputAudioBufferAppendRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Realtime/RealtimeContent.cs, OpenAI/Packages/com.openai.unity/Runtime/Realtime/ResponseAudioResponse.cs, OpenAI/Packages/com.openai.unity/Samples~/Assistant/AssistantBehaviour.cs, OpenAI/Packages/com.openai.unity/Samples~/Chat/ChatBehaviour.cs, OpenAI/Packages/com.openai.unity/Samples~/Chat/OpenAIChatSample.unity, OpenAI/Packages/com.openai.unity/Samples~/Realtime/OpenAIRealtimeSample.unity, OpenAI/Packages/com.openai.unity/Samples~/Realtime/RealtimeBehaviour.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_04_Chat.cs, OpenAI/Packages/com.openai.unity/package.json, OpenAI/Packages/manifest.json
- Fix http/https protocol in client settings
- Fix audio modality support in chat streaming completions
- Fix assistant samples
- Fix microphone sampling rates
- https://github.com/RageAgainstThePixel/com.utilities.audio/pull/36
- https://github.com/RageAgainstThePixel/com.utilities.encoder.wav/pull/24
- Fix playback sampling rates
=> com.openai.unity 8.4.5

OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Common/Function.cs, OpenAI/Packages/com.openai.unity/Runtime/Common/ReasoningEffort.cs, OpenAI/Packages/com.openai.unity/Runtime/Common/ReasoningEffort.cs.meta, OpenAI/Packages/com.openai.unity/Runtime/Common/Role.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_00_02_Extensions.cs, OpenAI/Packages/com.openai.unity/package.json
- Added Role.Developer for reasoning model messages
- Added reasoning effort parameter for o1 series models in ChatRequest
- Fix possible misinterpretation of function parameter types in function calls
=> com.openai.unity 8.5.0

OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatRequest.cs, OpenAI/Packages/com.openai.unity/package.json
- Fix ChatRequest serialization for ReasoningEffort
=> com.openai.unity 8.5.1

OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatRequest.cs, OpenAI/Packages/com.openai.unity/Runtime/Common/ReasoningEffort.cs, OpenAI/Packages/com.openai.unity/Runtime/Models/Model.cs, OpenAI/Packages/com.openai.unity/package.json
- Update ChatRequest to support o3 series reasoning models
=> com.openai.unity 8.5.4

.gitignore, OpenAI/Packages/com.openai.unity/Runtime/Assistants/AssistantResponse.cs, OpenAI/Packages/com.openai.unity/Runtime/Extensions/ResponseExtensions.cs, OpenAI/Packages/com.openai.unity/Samples~/Assistant/AssistantBehaviour.cs, OpenAI/Packages/com.openai.unity/Samples~/Chat/ChatBehaviour.cs, OpenAI/Packages/com.openai.unity/package.json, OpenAI/Packages/manifest.json
- Fixed Threads.AssistantResponse serialization with reasoning_effort
- Updated AssitantBehaviour sample
- Updated ChatBehaviour sample
- Added additional deserializing json logging when a failure occurs
=> com.openai.unity 8.6.3

OpenAI/Packages/com.openai.unity/Runtime/Threads/ThreadExtensions.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_03_Threads.cs, OpenAI/Packages/com.openai.unity/package.json, OpenAI/Packages/manifest.json
- Fixed Assistant Reasoning Model request serialization when using thread.CreateRunAsync
=> com.openai.unity 8.6.4

OpenAI/Packages/com.openai.unity/package.json, OpenAI/Packages/manifest.json
- updated com.utilities.rest -> 3.3.3
- updated com.utilities.encoder.wav -> 2.2.2
=> com.openai.unity 8.6.5

OpenAI/Packages/com.openai.unity/Runtime/Extensions/StringOrObjectConverter.cs, OpenAI/Packages/com.openai.unity/Runtime/Responses/Response.cs, OpenAI/Packages/com.openai.unity/Tests/TestFixture_14_Responses.cs, OpenAI/Packages/com.openai.unity/package.json
- Fixed Response.Instructions deserialization when using CreateResponseRequest.Prompt
=> com.openai.unity 8.7.3

OpenAI/Packages/com.openai.unity/Runtime/Realtime/InputAudioTranscriptionSettings.cs, OpenAI/Packages/com.openai.unity/Runtime/Realtime/Options.cs, OpenAI/Packages/com.openai.unity/Runtime/Realtime/SessionConfiguration.cs
- Extended Audio transcription Settings for better transcription
- Session config constructor should be accommodated as well for these change
=> Extended Audio transcription Settings for better transcription
